# -*- coding: utf-8 -*-
"""MULTI_DISCI_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSfeZwhV_8YcelBDxwAL8TdRulI2FFFb
"""

# =======================================
# 🍏🌽 Predict Disease from Uploaded Image
# =======================================

from google.colab import files
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

# 1️⃣ Give the model path
# Example: if saved in /content/
model_path = "/content/disease_model.h5"  # 🔹 Change path if stored elsewhere
model = tf.keras.models.load_model(model_path)
print("✅ Model loaded successfully from:", model_path)

# 2️⃣ Upload image for prediction
print("\n📤 Upload an image to predict (e.g., apple_leaf.jpg or corn_leaf.jpg)...")
uploaded_img = files.upload()
img_path = list(uploaded_img.keys())[0]

# 3️⃣ Preprocess image
img = image.load_img(img_path, target_size=(128, 128))  # must match training size
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0) / 255.0

# 4️⃣ Predict
pred = model.predict(img_array)
predicted_class = np.argmax(pred, axis=1)[0]

# 5️⃣ Class mapping (update if you trained on more classes)
class_labels = ['APPLE_DISEASE', 'CORN_DISEASE']

# 6️⃣ Show result
plt.imshow(image.load_img(img_path))
plt.axis("off")
plt.title(f"Predicted: {class_labels[predicted_class]}")
plt.show()

print(f"🌱 Predicted disease: {class_labels[predicted_class]}")
print(f"Confidence: {pred[0][predicted_class]*100:.2f}%")